//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easycounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amortization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Amortization()
        {
            this.Actives = new HashSet<Active>();
        }
    
        public int amortizationID { get; set; }
        public Nullable<System.DateTime> purchaseDate { get; set; }
        public Nullable<System.DateTime> saleDate { get; set; }
        public Nullable<decimal> amortizationRateYearly { get; set; }
        public Nullable<double> amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Active> Actives { get; set; }
    }
}
