//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easycounting.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.ItemsInBills = new HashSet<ItemsInBill>();
            this.Transactions = new HashSet<Transaction>();
        }
        [NotMapped]
        public int ItemsCount { get; set; }
        [NotMapped]
        public bool fieldChanged { get; set; }
        public int billID { get; set; }
        public string billNo { get; set; }
        public System.DateTime billDate { get; set; }
        public System.DateTime dueDate { get; set; }
        public string status { get; set; }
        public int discount { get; set; }
        public int vendorID { get; set; }
        public Nullable<int> expenseID { get; set; }
        public int companyID { get; set; }
        public string notes { get; set; }
        public double total { get; set; }
        public Nullable<int> taxID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ExpenseCategory ExpenseCategory { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsInBill> ItemsInBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
