//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easycounting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEnt : DbContext
    {
        public DbEnt()
            : base("name=DbEnt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Active> Actives { get; set; }
        public virtual DbSet<Amortization> Amortizations { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeesInCompany> EmployeesInCompanies { get; set; }
        public virtual DbSet<ExpenseCategory> ExpenseCategories { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemsCategory> ItemsCategories { get; set; }
        public virtual DbSet<ItemsInBill> ItemsInBills { get; set; }
        public virtual DbSet<ItemsInInvoice> ItemsInInvoices { get; set; }
        public virtual DbSet<Passive> Passives { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Payroll> Payrolls { get; set; }
        public virtual DbSet<Revenue> Revenues { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SaleCategory> SaleCategories { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersInCompany> UsersInCompanies { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    }
}
