//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easycounting.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.ItemsInInvoices = new HashSet<ItemsInInvoice>();
        }
        [NotMapped]
        public int ItemsCount { get; set; }
        [NotMapped]
        public bool fieldChanged { get; set; }
        public int invoiceID { get; set; }
        public string invoiceNo { get; set; }
        public System.DateTime invoiceDate { get; set; }
        public System.DateTime dueDate { get; set; }
        public string status { get; set; }
        public Nullable<int> discount { get; set; }
        public int customerID { get; set; }
        public int saleID { get; set; }
        public int companyID { get; set; }
        public string notes { get; set; }
        public double total { get; set; }
        public Nullable<int> taxID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual SaleCategory SaleCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsInInvoice> ItemsInInvoices { get; set; }
    }
}
