//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easycounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsInBill
    {
        public int id { get; set; }
        public int billID { get; set; }
        public int itemID { get; set; }
        public int qt { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Item Item { get; set; }
    }
}
