//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easycounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.ItemsInBills = new HashSet<ItemsInBill>();
            this.ItemsInInvoices = new HashSet<ItemsInInvoice>();
        }
    
        public int itemID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public double purchasePrice { get; set; }
        public double salePrice { get; set; }
        public Nullable<int> categoryID { get; set; }
        public int companyID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ItemsCategory ItemsCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsInBill> ItemsInBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsInInvoice> ItemsInInvoices { get; set; }
    }
}
