//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easycounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passive
    {
        public int passiveID { get; set; }
        public string accNo { get; set; }
        public string description { get; set; }
        public double amount { get; set; }
        public string category { get; set; }
        public Nullable<int> companyID { get; set; }
        public Nullable<System.DateTime> datePerformed { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
