//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easycounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int paymentID { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> accountID { get; set; }
        public Nullable<int> vendorID { get; set; }
        public string description { get; set; }
        public Nullable<int> expenseID { get; set; }
        public string status { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ExpenseCategory ExpenseCategory { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
