//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easycounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue
    {
        public int revenueID { get; set; }
        public System.DateTime date { get; set; }
        public int customerID { get; set; }
        public string status { get; set; }
        public double total { get; set; }
        public int salesD { get; set; }
        public string description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SaleCategory SaleCategory { get; set; }
    }
}
