//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easycounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public int taxID { get; set; }
        public string name { get; set; }
        public int value { get; set; }
        public string description { get; set; }
        public int companyID { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
