//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easycounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string transactionID { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> billID { get; set; }
        public Nullable<int> paymentID { get; set; }
        public Nullable<int> payrollID { get; set; }
        public int userID { get; set; }
        public int accountID { get; set; }
        public string status { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Bill Bill { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Payroll Payroll { get; set; }
        public virtual User User { get; set; }
    }
}
